### ISSUE TITLE
Install instruction gives an error

### ISSUE THREAD

**Issue by olalonde** [src-d/kmcuda#11]
On Mac with Python 3, the pip install command doesn't work:

```
$ pip install git+https://github.com/src-d/kmcuda.git
Collecting git+https://github.com/src-d/kmcuda.git
  Cloning https://github.com/src-d/kmcuda.git to /private/var/folders/67/wj749ptn3jlb4_nlf9nphyy00000gn/T/pip-_77ac4rm-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/67/wj749ptn3jlb4_nlf9nphyy00000gn/T/pip-_77ac4rm-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/67/wj749ptn3jlb4_nlf9nphyy00000gn/T/pip-_77ac4rm-build/

```

**Comment by olalonde** [comment]
I'm also getting a build error on mac when trying to compile:

```
~/code/kmcuda/src$ CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ LDFLAGS=-L/usr/local/opt/llvm/lib/ cmake -DCMAKE_BUILD_TYPE=Release .                                    develop
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenMP (missing: OpenMP_C_FLAGS OpenMP_CXX_FLAGS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindOpenMP.cmake:316 (find_package_handle_standard_args)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/olalonde/code/kmcuda/src/CMakeFiles/CMakeOutput.log".
See also "/Users/olalonde/code/kmcuda/src/CMakeFiles/CMakeError.log".
```

**Comment by vmarkovtsev** [comment]
This is weird because it works In Travis. The first error means that there is no setup.py in the root dir. Indeed, it is not after the latest refactoring, at the moment you have to change to `src`. The second error violates the condition stated in the Readme. Your clang does not support open positions. This has nothing to do with kmcuda, probably Home brew screwed it up lately. Try to build a sample openmp prog using it.

**Comment by olalonde** [comment]
Ah, I see. I will try to find a workaround. By the way, if the travis build works for OS X, it seems like it wouldn't be that hard to distribute the compiled module for OS X as well?

**Comment by olalonde** [comment]
```
~/code/kmcuda/src$ brew install llvm --with-clang                                                                                                                                         develop
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/science).
No changes to formulae.

Warning: llvm is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
(venv) ~/code/kmcuda/src$ brew install llvm --with-clang --force                                                                                                                                 develop
Warning: llvm: this formula has no --with-clang option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/llvm-4.0.0.sierra.bottle.tar.gz
```

Looks like llvm no longer has `--with-clang` option.

**Comment by olalonde** [comment]
Ok, so I think my Macbook Pro doesn't even have a CUDA compatible GPU :| Sorry to waste your time.
 
<img width="668" alt="screen shot 2017-04-09 at 12 05 16" src="https://cloud.githubusercontent.com/assets/416585/24840164/d17d6e3e-1d1c-11e7-81b8-66ccdc70729c.png">

**Comment by vmarkovtsev** [comment]
@olalonde I fixed the `pip install` cmdline so that the original issue is resolved. The solution is
```
pip3 install git+https://github.com/src-d/kmcuda.git#subdirectory=src
```
