### ISSUE TITLE
compute capability mismatch for device 0: wanted 7.5, have 8.6

### ISSUE THREAD

**Issue by TTTTTTina** [src-d/kmcuda#120]
hello,
I run "CUDA_ARCH=86 pip install libKMCUDA" successfully but when I try to run the program it tells me this:

```
compute capability mismatch for device 0: wanted 7.5, have 8.6
>>>> you may want to build kmcuda with -DCUDA_ARCH=86 (refer to "Building" in README.md)
compute capability mismatch for device 1: wanted 7.5, have 8.6
>>>> you may want to build kmcuda with -DCUDA_ARCH=86 (refer to "Building" in README.md)
python-BaseException
Traceback (most recent call last):
  File "/home/aa/xlhuang/pycharm-community-2021.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/aa/xlhuang/pycharm-community-2021.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/aa/xlhuang/classifier/Cluster_visualize.py", line 47, in <module>
    centroids, assignments = kmeans_cuda(feature_data, 100, verbosity=1, seed=3)
ValueError: No such CUDA device exists
Backend TkAgg is interactive backend. Turning interactive mode on. 
```

so it does not support 8.6? or I need to use these commands:
```
git clone https://github.com/src-d/kmcuda
cd src
cmake -DCMAKE_BUILD_TYPE=Release -D DISABLE_R-y -D CUDA_ARCH=86 . && make
```

**Comment by TTTTTTina** [comment]
I tried these commands
```
git clone https://github.com/src-d/kmcuda
cd src
cmake -DCMAKE_BUILD_TYPE=Release -D DISABLE_R-y -D CUDA_ARCH=86 . && make
```
and got this
```
nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture'
CMake Error at KMCUDA_generated_transpose.cu.o.Release.cmake:220 (message):
  Error generating
  /home/aa/xlhuang/classifier/kmcuda/src/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_transpose.cu.o


make[2]: *** [CMakeFiles/KMCUDA.dir/build.make:91: CMakeFiles/KMCUDA.dir/KMCUDA_generated_transpose.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/KMCUDA.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```
