### ISSUE TITLE
Problem install with pip libKMCUDA

### ISSUE THREAD

**Issue by gabriellimagomes15** [src-d/kmcuda#45]
Hello everybody. 
I am using **CUDA 8.0, GCC 7.3 and CMAKE 3.12**

I am trying install libKMCUDO with pip, but I get this error: 

`pip install libKMCUDA`

```
Collecting libKMCUDA
  Using cached https://files.pythonhosted.org/packages/c0/07/66fce78d11f1ba57fdc14a29f3fcda04685cddee7d754fb47ce470ff1c1e/libKMCUDA-6.2.1.tar.gz
Requirement already satisfied: numpy in /home/gabrielgomes/anaconda3/lib/python3.6/site-packages (from libKMCUDA) (1.14.3)
Building wheels for collected packages: libKMCUDA
  Running setup.py bdist_wheel for libKMCUDA ... error
  Complete output from command /home/gabrielgomes/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-_44ad4nk --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  CMake Error: The source directory "/tmp/pip-install-r8jx0k34/libKMCUDA" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py", line 80, in <module>
      "Programming Language :: Python :: 3.6",
    File "/home/gabrielgomes/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/gabrielgomes/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py", line 19, in run
      self._build()
    File "/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py", line 34, in _build
      "-DCUDA_TOOLKIT_ROOT_DIR=%s" % cuda_toolkit_dir, "."))
    File "/home/gabrielgomes/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DDISABLE_R=y', '-DCUDA_TOOLKIT_ROOT_DIR=/home/cuda-8.0/', '.')' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for libKMCUDA
  Running setup.py clean for libKMCUDA
Failed to build libKMCUDA
Installing collected packages: libKMCUDA
  Running setup.py install for libKMCUDA ... error
    Complete output from command /home/gabrielgomes/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_4gwjv2t/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    CMake Error: The source directory "/tmp/pip-install-r8jx0k34/libKMCUDA" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py", line 80, in <module>
        "Programming Language :: Python :: 3.6",
      File "/home/gabrielgomes/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/gabrielgomes/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py", line 19, in run
        self._build()
      File "/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py", line 34, in _build
        "-DCUDA_TOOLKIT_ROOT_DIR=%s" % cuda_toolkit_dir, "."))
      File "/home/gabrielgomes/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DDISABLE_R=y', '-DCUDA_TOOLKIT_ROOT_DIR=/home/cuda-8.0/', '.')' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/home/gabrielgomes/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r8jx0k34/libKMCUDA/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_4gwjv2t/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-r8jx0k34/libKMCUDA/

```
Anybody can help me?

Thanks very much!!

**Comment by vmarkovtsev** [comment]
I think I missed `CMakeLists.txt` from the source  package. Try this:

```
git+https://github.com/src-d/kmcuda.git#subdirectory=src
```

**Comment by gabriellimagomes15** [comment]
Hello, thanks your response.  

I have tried this, so I got new error:

```
  [ 50%] Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_knn.cu.o
  In file included from /home/cuda-8.0/include/cuda_runtime.h:78:0,
                   from <command-line>:0:
  /home/cuda-8.0/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
   #error -- unsupported GNU version! gcc versions later than 5 are not supported!
    ^~~~~
  In file included from /home/cuda-8.0/include/cuda_runtime.h:78:0,
                   from <command-line>:0:
  /home/cuda-8.0/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
   #error -- unsupported GNU version! gcc versions later than 5 are not supported!
    ^~~~~
  In file included from /home/cuda-8.0/include/cuda_runtime.h:78:0,
                   from <command-line>:0:
  /home/cuda-8.0/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
   #error -- unsupported GNU version! gcc versions later than 5 are not supported!
    ^~~~~
  CMake Error at KMCUDA_generated_transpose.cu.o.Release.cmake:219 (message):
    Error generating
    /tmp/pip-req-build-z80w155a/src/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_transpose.cu.o
  
  
  make[2]: *** [CMakeFiles/KMCUDA.dir/KMCUDA_generated_transpose.cu.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  CMake Error at KMCUDA_generated_knn.cu.o.Release.cmake:219 (message):
    Error generating
    /tmp/pip-req-build-z80w155a/src/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_knn.cu.o
  
  
  make[2]: *** [CMakeFiles/KMCUDA.dir/KMCUDA_generated_knn.cu.o] Error 1
  CMake Error at KMCUDA_generated_kmeans.cu.o.Release.cmake:219 (message):
    Error generating
    /tmp/pip-req-build-z80w155a/src/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_kmeans.cu.o
  
  
  make[2]: *** [CMakeFiles/KMCUDA.dir/KMCUDA_generated_kmeans.cu.o] Error 1
  make[1]: *** [CMakeFiles/KMCUDA.dir/all] Error 2
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-z80w155a/src/setup.py", line 80, in <module>
      "Programming Language :: Python :: 3.6",
    File "/home/gabrielgomes/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/gabrielgomes/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabrielgomes/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-z80w155a/src/setup.py", line 19, in run
      self._build()
    File "/tmp/pip-req-build-z80w155a/src/setup.py", line 44, in _build
      check_call(("make", "-j%d" % cpu_count()))
    File "/home/gabrielgomes/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '('make', '-j80')' returned non-zero exit status 2.
```

**Comment by vmarkovtsev** [comment]
As you see from the log

```
#error -- unsupported GNU version! gcc versions later than 5 are not supported!
```
CUDA 8.0 is incompatible with GCC >5.

**Comment by gabriellimagomes15** [comment]
oohhhh :O 

I going to downgrade and test.

Thanks very much :)
