### ISSUE TITLE
undefined symbol: _ZTVN10__cxxabiv119__pointer_type_infoE

### ISSUE THREAD

**Issue by iesahin** [src-d/kmcuda#69]
First `cmake`

```
» CC=/usr/bin/gcc-5 CXX=/usr/bin/gcc-5 cmake -DCUDA_ARCH=52 -DDISABLE_R=y ..                                                ‹master✓› ➤ c286c3e  [6d12h47m] 
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/gcc-5
-- Check for working CXX compiler: /usr/bin/gcc-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PythonInterp: /home/iesahin/Environments/makimface/bin/python3 (found suitable version "3.6.7", minimum required is "3") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.7", minimum required is "3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/iesahin/Repository/kmcuda/src/build
```

Then, `make`

```
» make                                                                                                                      ‹master✓› ➤ c286c3e  [6d12h47m] 
[ 16%] Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_transpose.cu.o
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z9transposeILb0EEvPKfjjPf' for 'sm_52'
ptxas info    : Function properties for _Z9transposeILb0EEvPKfjjPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 24 registers, 4224 bytes smem, 344 bytes cmem[0]
ptxas info    : Compiling entry function '_Z9transposeILb1EEvPKfjjPf' for 'sm_52'
ptxas info    : Function properties for _Z9transposeILb1EEvPKfjjPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 24 registers, 4224 bytes smem, 344 bytes cmem[0]
ptxas info    : Compiling entry function '_Z13copy_sample_tjjtPKfPf' for 'sm_52'
ptxas info    : Function properties for _Z13copy_sample_tjjtPKfPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 7 registers, 352 bytes cmem[0]
[ 33%] Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_kmeans.cu.o
ptxas info    : 77784 bytes gmem, 92 bytes cmem[3]
ptxas info    : Compiling entry function '_Z28kmeans_calc_average_distanceIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PKjPf' for 'sm_52'
ptxas info    : Function properties for _Z28kmeans_calc_average_distanceIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PKjPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 29 registers, 360 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z28kmeans_calc_average_distanceIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PKjPf' for 'sm_52'
ptxas info    : Function properties for _Z28kmeans_calc_average_distanceIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PKjPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 29 registers, 360 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z22kmeans_yy_local_filterIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS3_S5_PKfPjPf' for 'sm_52'
ptxas info    : Function properties for _Z22kmeans_yy_local_filterIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS3_S5_PKfPjPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 39 registers, 384 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z22kmeans_yy_local_filterIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS3_S5_PKfPjPf' for 'sm_52'
ptxas info    : Function properties for _Z22kmeans_yy_local_filterIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS3_S5_PKfPjPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 39 registers, 384 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z23kmeans_yy_global_filterIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PKjPKfS5_PjPfS8_' for 'sm_52'
ptxas info    : Function properties for _Z23kmeans_yy_global_filterIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PKjPKfS5_PjPfS8_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 392 bytes cmem[0], 32 bytes cmem[2]
ptxas info    : Compiling entry function '_Z23kmeans_yy_global_filterIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PKjPKfS5_PjPfS8_' for 'sm_52'
ptxas info    : Function properties for _Z23kmeans_yy_global_filterIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PKjPKfS5_PjPfS8_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 31 registers, 392 bytes cmem[0], 12 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21kmeans_yy_calc_driftsIL20KMCUDADistanceMetric1EfEvjjPKT0_PS1_' for 'sm_52'
ptxas info    : Function properties for _Z21kmeans_yy_calc_driftsIL20KMCUDADistanceMetric1EfEvjjPKT0_PS1_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 23 registers, 344 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z21kmeans_yy_calc_driftsIL20KMCUDADistanceMetric0EfEvjjPKT0_PS1_' for 'sm_52'
ptxas info    : Function properties for _Z21kmeans_yy_calc_driftsIL20KMCUDADistanceMetric0EfEvjjPKT0_PS1_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 21 registers, 344 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z14kmeans_yy_initIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PKjS5_Pf' for 'sm_52'
ptxas info    : Function properties for _Z14kmeans_yy_initIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PKjS5_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 39 registers, 368 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z14kmeans_yy_initIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PKjS5_Pf' for 'sm_52'
ptxas info    : Function properties for _Z14kmeans_yy_initIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PKjS5_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 37 registers, 368 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13kmeans_adjustIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS5_PS1_Pj' for 'sm_52'
ptxas info    : Function properties for _Z13kmeans_adjustIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS5_PS1_Pj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 368 bytes cmem[0], 20 bytes cmem[2]
ptxas info    : Compiling entry function '_Z13kmeans_adjustIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS5_PS1_Pj' for 'sm_52'
ptxas info    : Function properties for _Z13kmeans_adjustIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS5_PS1_Pj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 368 bytes cmem[0], 12 bytes cmem[2]
ptxas info    : Compiling entry function '_Z19kmeans_assign_lloydIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PjS4_' for 'sm_52'
ptxas info    : Function properties for _Z19kmeans_assign_lloydIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PjS4_
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 360 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z19kmeans_assign_lloydIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PjS4_' for 'sm_52'
ptxas info    : Function properties for _Z19kmeans_assign_lloydIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PjS4_
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 360 bytes cmem[0]
ptxas info    : Compiling entry function '_Z26kmeans_assign_lloyd_smallcIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PjS4_' for 'sm_52'
ptxas info    : Function properties for _Z26kmeans_assign_lloyd_smallcIL20KMCUDADistanceMetric1EfEvjjPKT0_S3_PjS4_
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 360 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z26kmeans_assign_lloyd_smallcIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PjS4_' for 'sm_52'
ptxas info    : Function properties for _Z26kmeans_assign_lloyd_smallcIL20KMCUDADistanceMetric0EfEvjjPKT0_S3_PjS4_
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 360 bytes cmem[0]
ptxas info    : Compiling entry function '_Z33kmeans_afkmc2_min_dist_transposedIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS3_Pf' for 'sm_52'
ptxas info    : Function properties for _Z33kmeans_afkmc2_min_dist_transposedIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS3_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 30 registers, 360 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z33kmeans_afkmc2_min_dist_transposedIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS3_Pf' for 'sm_52'
ptxas info    : Function properties for _Z33kmeans_afkmc2_min_dist_transposedIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS3_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 29 registers, 360 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z22kmeans_afkmc2_min_distIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS3_Pf' for 'sm_52'
ptxas info    : Function properties for _Z22kmeans_afkmc2_min_distIL20KMCUDADistanceMetric1EfEvjjPKT0_PKjS3_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 360 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z22kmeans_afkmc2_min_distIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS3_Pf' for 'sm_52'
ptxas info    : Function properties for _Z22kmeans_afkmc2_min_distIL20KMCUDADistanceMetric0EfEvjjPKT0_PKjS3_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 31 registers, 360 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z26kmeans_afkmc2_calc_q_distsIL20KMCUDADistanceMetric1EfEvjjjPKT0_PfS4_' for 'sm_52'
ptxas info    : Function properties for _Z26kmeans_afkmc2_calc_q_distsIL20KMCUDADistanceMetric1EfEvjjjPKT0_PfS4_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 27 registers, 360 bytes cmem[0], 36 bytes cmem[2]
ptxas info    : Compiling entry function '_Z26kmeans_afkmc2_calc_q_distsIL20KMCUDADistanceMetric0EfEvjjjPKT0_PfS4_' for 'sm_52'
ptxas info    : Function properties for _Z26kmeans_afkmc2_calc_q_distsIL20KMCUDADistanceMetric0EfEvjjjPKT0_PfS4_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 28 registers, 360 bytes cmem[0], 16 bytes cmem[2]
ptxas info    : Compiling entry function '_Z16kmeans_plus_plusIL20KMCUDADistanceMetric1EfEvjjjPKT0_S3_PfS4_' for 'sm_52'
ptxas info    : Function properties for _Z16kmeans_plus_plusIL20KMCUDADistanceMetric1EfEvjjjPKT0_S3_PfS4_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 29 registers, 368 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z16kmeans_plus_plusIL20KMCUDADistanceMetric0EfEvjjjPKT0_S3_PfS4_' for 'sm_52'
ptxas info    : Function properties for _Z16kmeans_plus_plusIL20KMCUDADistanceMetric0EfEvjjjPKT0_S3_PfS4_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 29 registers, 368 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z31kmeans_yy_find_group_max_driftsjjPKjPf' for 'sm_52'
ptxas info    : Function properties for _Z31kmeans_yy_find_group_max_driftsjjPKjPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 32 registers, 344 bytes cmem[0]
ptxas info    : Compiling entry function '_Z25kmeans_afkmc2_random_stepjmmPKfPjPf' for 'sm_52'
ptxas info    : Function properties for _Z25kmeans_afkmc2_random_stepjmmPKfPjPf
    6440 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 56 registers, 32768 bytes smem, 368 bytes cmem[0], 60 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20kmeans_afkmc2_calc_qjjfPf' for 'sm_52'
ptxas info    : Function properties for _Z20kmeans_afkmc2_calc_qjjfPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 15 registers, 344 bytes cmem[0], 20 bytes cmem[2]
[ 50%] Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_knn.cu.o
ptxas info    : 8 bytes gmem, 12 bytes cmem[3]
ptxas info    : Compiling entry function '_Z16knn_assign_shmemIL20KMCUDADistanceMetric1EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj' for 'sm_52'
ptxas info    : Function properties for _Z16knn_assign_shmemIL20KMCUDADistanceMetric1EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 400 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z16knn_assign_shmemIL20KMCUDADistanceMetric0EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj' for 'sm_52'
ptxas info    : Function properties for _Z16knn_assign_shmemIL20KMCUDADistanceMetric0EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 400 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z15knn_assign_gmemIL20KMCUDADistanceMetric1EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj' for 'sm_52'
ptxas info    : Function properties for _Z15knn_assign_gmemIL20KMCUDADistanceMetric1EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 400 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z15knn_assign_gmemIL20KMCUDADistanceMetric0EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj' for 'sm_52'
ptxas info    : Function properties for _Z15knn_assign_gmemIL20KMCUDADistanceMetric0EfEvjjtPKfS2_PKT0_S5_PKjS7_S7_Pj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 47 registers, 400 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z26knn_calc_cluster_distancesIL20KMCUDADistanceMetric1EfEvjPKT0_Pf' for 'sm_52'
ptxas info    : Function properties for _Z26knn_calc_cluster_distancesIL20KMCUDADistanceMetric1EfEvjPKT0_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 38 registers, 49152 bytes smem, 344 bytes cmem[0], 28 bytes cmem[2]
ptxas info    : Compiling entry function '_Z26knn_calc_cluster_distancesIL20KMCUDADistanceMetric0EfEvjPKT0_Pf' for 'sm_52'
ptxas info    : Function properties for _Z26knn_calc_cluster_distancesIL20KMCUDADistanceMetric0EfEvjPKT0_Pf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 38 registers, 49152 bytes smem, 344 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25knn_calc_cluster_radiusesIL20KMCUDADistanceMetric1EfEvjjPKjS2_PKT0_S5_PfS6_' for 'sm_52'
ptxas info    : Function properties for _Z25knn_calc_cluster_radiusesIL20KMCUDADistanceMetric1EfEvjjPKjS2_PKT0_S5_PfS6_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 32768 bytes smem, 376 bytes cmem[0], 36 bytes cmem[2]
ptxas info    : Compiling entry function '_Z25knn_calc_cluster_radiusesIL20KMCUDADistanceMetric0EfEvjjPKjS2_PKT0_S5_PfS6_' for 'sm_52'
ptxas info    : Function properties for _Z25knn_calc_cluster_radiusesIL20KMCUDADistanceMetric0EfEvjjPKjS2_PKT0_S5_PfS6_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 40 registers, 32768 bytes smem, 376 bytes cmem[0], 16 bytes cmem[2]
ptxas info    : Compiling entry function '_Z29knn_assign_gmem_deinterleave2jtPj' for 'sm_52'
ptxas info    : Function properties for _Z29knn_assign_gmem_deinterleave2jtPj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 22 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z29knn_assign_gmem_deinterleave1jtPj' for 'sm_52'
ptxas info    : Function properties for _Z29knn_assign_gmem_deinterleave1jtPj
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 23 registers, 336 bytes cmem[0]
ptxas info    : Compiling entry function '_Z28knn_mirror_cluster_distancesPf' for 'sm_52'
ptxas info    : Function properties for _Z28knn_mirror_cluster_distancesPf
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 25 registers, 328 bytes cmem[0], 8 bytes cmem[2]
Scanning dependencies of target KMCUDA
[ 66%] Building CXX object CMakeFiles/KMCUDA.dir/kmcuda.cc.o
[ 83%] Building CXX object CMakeFiles/KMCUDA.dir/python.cc.o
[100%] Linking CXX shared library libKMCUDA.so
[100%] Built target KMCUDA
```

seems OK. 

Now, Python
```
» python3                                                                                                          
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libKMCUDA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/iesahin/Repository/kmcuda/src/build/libKMCUDA.so: undefined symbol: _ZTVN10__cxxabiv119__pointer_type_infoE
>>> 
```

This is in Ubuntu 18.04 with CUDA 10. Device is GeForce 980 Ti, hence capability = 5.2. 

It's in a virtual environment, but I tried without it too and no difference. Probably a link error but where may I look at?

**Comment by iesahin** [comment]
By the way, when I install via `pip3`

```
CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda CUDA_ARCH=52 pip3 install --user 'git+https://github.com/src-d/kmcuda.git#subdirectory=src'             
            
Collecting git+https://github.com/src-d/kmcuda.git#subdirectory=src
  Cloning https://github.com/src-d/kmcuda.git to /tmp/pip-6t9eg3vb-build
Collecting numpy (from libKMCUDA==6.2.2)
  Using cached https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, libKMCUDA
  Running setup.py install for libKMCUDA ... done
Successfully installed libKMCUDA-6.2.2 numpy-1.16.2
```

it gives import error for `numpy.core.multiarray`

```
python3                                                                                                                                                   
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libKMCUDA
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
>>> 
```

**Comment by iesahin** [comment]
Sorry, the last one with `pip` is from botched numpy versions or something like that. I installed via `pip` as `root` and it looks OK. 

Is the problem from installng as user/virtual env?

**Comment by vmarkovtsev** [comment]
Most likely yes, it requires native compilation and detects numpy, which may leak through the virtual environment.
