### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by marsggbo** [src-d/kmcuda#70]
```
      self.distribution.run_command(command)
    File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-uxwhn1ic/libKMCUDA/setup.py", line 19, in run
      self._build()
    File "/tmp/pip-install-uxwhn1ic/libKMCUDA/setup.py", line 33, in _build
      "CUDA_TOOLKIT_ROOT_DIR environment variable must be defined")
  __main__.SetupConfigurationError: CUDA_TOOLKIT_ROOT_DIR environment variable must be defined

  ----------------------------------------
  Failed building wheel for libKMCUDA
  Running setup.py clean for libKMCUDA
Failed to build libKMCUDA
Installing collected packages: libKMCUDA
  Running setup.py install for libKMCUDA ... error
    Complete output from command /home/xinhe/anaconda3/envs/skin100/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-uxwhn1ic/libKMCUDA/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-j8nhajb7/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uxwhn1ic/libKMCUDA/setup.py", line 83, in <module>
        "Programming Language :: Python :: 3.6",
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/xinhe/anaconda3/envs/skin100/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-uxwhn1ic/libKMCUDA/setup.py", line 19, in run
        self._build()
      File "/tmp/pip-install-uxwhn1ic/libKMCUDA/setup.py", line 33, in _build
        "CUDA_TOOLKIT_ROOT_DIR environment variable must be defined")
    __main__.SetupConfigurationError: CUDA_TOOLKIT_ROOT_DIR environment variable must be defined

    ----------------------------------------
Command "/home/xinhe/anaconda3/envs/skin100/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-uxwhn1ic/libKMCUDA/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-j8nhajb7/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-uxwhn1ic/libKMCUDA/

```

**Comment by vmarkovtsev** [comment]
Hi @marsggbo.

Building in Anaconda environment is officially not supported because the native compilation is often broken there, in general. . I am closing this as WONTFIX. However, feel free to PR a fix or discuss the problem further in the issues.

**Comment by 448357739** [comment]
> Hi @marsggbo.
> 
> Building in Anaconda environment is officially not supported because the native compilation is often broken there, in general. . I am closing this as WONTFIX. However, feel free to PR a fix or discuss the problem further in the issues.

Hi @vmarkovtsev.
I have the same question. The Cmake file has been successfully complied,but I fail to  install libKMCUDA with pip.Could you please tell me how to deal with the condition?I've trapped for a whole day.

**Comment by vmarkovtsev** [comment]
The log in the original issue ends with:

```
__main__.SetupConfigurationError: CUDA_TOOLKIT_ROOT_DIR environment variable must be defined
```

So you need to do what it says. If you are not sure what is a CUDA toolkit directory, please google.

If your problem is different, you need to open another issue, but yeah, if the environment is not supported, I am going to close it at once.
